/*
 * Load profile for the endpoints that actually matter under traffic.
 *
 * Target, stated explicitly rather than "thousands of requests": 5,000
 * requests/minute sustained (~83 rps) with a burst to 2x, split roughly as
 * real traffic is — mostly content reads, a small fraction of writes.
 *
 *   k6 run -e BASE_URL=https://staging-api.taifer.com load/k6-leads.js
 *
 * Thresholds are the pass/fail contract. The lead endpoint gets a stricter
 * error budget than the read endpoints because a dropped enquiry is lost
 * revenue, whereas a slow listing is a slow listing.
 */
import http from 'k6/http';
import { check, group } from 'k6';
import { Rate } from 'k6/metrics';

const BASE_URL = __ENV.BASE_URL || 'http://localhost:4000';

const leadFailures = new Rate('lead_submit_failures');

export const options = {
  scenarios: {
    /* The bulk of real traffic: people browsing. */
    content_reads: {
      executor: 'ramping-arrival-rate',
      startRate: 10,
      timeUnit: '1s',
      preAllocatedVUs: 50,
      maxVUs: 300,
      stages: [
        { target: 80, duration: '1m' },   // ramp to the sustained target
        { target: 80, duration: '3m' },   // hold
        { target: 160, duration: '1m' },  // burst headroom
        { target: 0, duration: '30s' },
      ],
      exec: 'browse',
    },
    /* Writes are a small share of requests but carry the strictest budget. */
    lead_submissions: {
      executor: 'constant-arrival-rate',
      rate: 3,
      timeUnit: '1s',
      duration: '5m30s',
      preAllocatedVUs: 10,
      maxVUs: 50,
      exec: 'submitLead',
    },
  },
  thresholds: {
    'http_req_duration{scenario:content_reads}': ['p(95)<300', 'p(99)<800'],
    'http_req_duration{scenario:lead_submissions}': ['p(95)<800'],
    lead_submit_failures: ['rate<0.001'],
    http_req_failed: ['rate<0.01'],
  },
};

const LISTINGS = ['/api/v1/journeys', '/api/v1/destinations', '/api/v1/hotels', '/api/v1/group-tours'];

export function browse() {
  group('content', () => {
    const home = http.get(`${BASE_URL}/api/v1/home`);
    check(home, { 'home 200': (r) => r.status === 200 });

    const listing = LISTINGS[Math.floor(Math.random() * LISTINGS.length)];
    const page = 1 + Math.floor(Math.random() * 3);
    const response = http.get(`${BASE_URL}${listing}?page=${page}&limit=12`);

    check(response, {
      'listing 200': (r) => r.status === 200,
      'listing paginated': (r) => {
        try {
          return r.json().meta.limit === 12;
        } catch {
          return false;
        }
      },
    });
  });
}

export function submitLead() {
  /*
   * A unique email and idempotency key per iteration, so the run measures the
   * real insert path rather than repeatedly hitting the dedupe short-circuit.
   */
  const unique = `${__VU}-${__ITER}-${Date.now()}`;

  const response = http.post(
    `${BASE_URL}/api/v1/leads`,
    JSON.stringify({
      name: `Load Test ${unique}`,
      email: `load-${unique}@example.invalid`,
      phone: '+919876500000',
      message: 'Generated by the k6 load profile.',
      source: 'contact_form',
      context: { sourcePage: '/load-test' },
    }),
    {
      headers: { 'Content-Type': 'application/json', 'Idempotency-Key': `k6-${unique}` },
      tags: { name: 'POST /api/v1/leads' },
    },
  );

  // 429 is a correct answer under a deliberate flood, so it is not a failure of
  // the endpoint; anything else outside 2xx is.
  const ok = response.status === 201 || response.status === 200 || response.status === 429;
  leadFailures.add(!ok);

  check(response, {
    'lead accepted or throttled': () => ok,
    'lead returns an id when created': (r) => r.status !== 201 || Boolean(r.json().data.id),
  });
}
